const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');

const getConfig = (platform, mode) => ({
  entry: {
    background: './src/background.js',
    content: './src/content.js',
  },
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist', platform),
  },
  // Use CSP-safe source maps; never use eval in extension pages
  devtool: mode === 'development' ? 'cheap-module-source-map' : false,
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: `src/manifest.${platform}.json`,
          to: 'manifest.json',
        },
        { from: 'src/icons', to: 'icons' },
        // copy built popup (generated by ui/ build) into dist
        { from: 'src/popup', to: 'popup', noErrorOnMissing: true },
      ],
    }),
  ],
});

module.exports = (env, argv) => {
  const mode = (argv && argv.mode) || process.env.NODE_ENV || 'production';
  return ['chrome', 'firefox'].map(platform => getConfig(platform, mode));
};
